### ISSUE TITLE
No room activities Fix 13

### ISSUE THREAD

**Issue by huntervcx** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#15]
got this bug since the update of Fix #13 :
(totally specific with me, tested on other computer where this work but same error. i can't know wich module of the intra create this bug)

Traceback (most recent call last):
  File "./main.py", line 37, in <module>
    main()
  File "./main.py", line 32, in main
    calendar_craller.create_event(i, CALENDAR_ID)
  File "/home/huntervcx/Documents/Linker_EPITECH_To_GOOGLE_Calendar/calendar_craller.py", line 102, in create_event
    "location": event_param['room']['code'] if 'room' in event_param and 'code' in event_param['room'] else '',
TypeError: argument of type 'NoneType' is not iterable

**Comment by Thezap** [comment]
Can you add some debug to know the activities to cause that problem.
You can print the module and activities name, and the activities code.

I doesn't have this problem so it's difficult to fix it if I cannot teste

**Comment by Thezap** [comment]
Ok, I just push something, this should fix your problem,
Can you confirm it

**Comment by arthur-perrot** [comment]
Bug resolved itself before so don't know sorry

**Comment by arthur-perrot** [comment]
got new error :

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 26, in main
    epitech_activities_list = parser.get_epitech_event(EPITECH_AUTH)
  File "/home/huntervcx/Documents/Linker_EPITECH_To_GOOGLE_Calendar/parser.py", line 13, in get_epitech_event
    if ('event_registered' in i and i['event_registered'] is not False) or i['status_manager'] is not None:
KeyError: 'status_manager'
