### ISSUE TITLE
Linker breaking on 'status_manager'

### ISSUE THREAD

**Issue by emneo-dev** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#17]
When launching the Linker it traceback with :

> Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 26, in main
    epitech_activities_list = parser.get_epitech_event(EPITECH_AUTH)
  File "/home/huntears/Documents/perso/Linker_EPITECH_To_GOOGLE_Calendar/parser.py", line 13, in get_epitech_event
    if ('event_registered' in i and i['event_registered'] is not False) or i['status_manager'] is not None:
KeyError: 'status_manager'

I verified my auto-logging link, and the credentials.json, but couldn't find the bug. I also have all the dependencies and I'm running on Manjaro i3 (I also tried on Pop-OS, but same ending).

**Comment by Thezap** [comment]
I'm going to check that today
It's related to the response of the intranet

**Comment by emneo-dev** [comment]
It still tracebacks :

> Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 26, in main
    epitech_activities_list = parser.get_epitech_event(EPITECH_AUTH)
  File "/home/huntears/Linker_EPITECH_To_GOOGLE_Calendar/parser.py", line 14, in get_epitech_event
    if i['status_manager'] is not None:
KeyError: 'status_manager'

Sorry mate
