### ISSUE TITLE
Error : KeyError: 'status_manager'

### ISSUE THREAD

**Issue by bengeois** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#20]
Hey,

When I launch the linker, I have : 
`Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 26, in main
    epitech_activities_list = parser.get_epitech_event(EPITECH_AUTH)
  File "/home/bourgeois/Desktop/Linker_EPITECH_To_GOOGLE_Calendar/parser.py", line 14, in get_epitech_event
    if i['status_manager'] is not None:
KeyError: 'status_manager'
`
Thanks

**Comment by Thezap** [comment]
This should be fix with #21
